# Generated by Django 3.2.9 on 2021-11-17 01:09

from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio_currency', djmoney.models.fields.CurrencyField(choices=[('CLP', 'Chilean Peso')], default='CLP', editable=False, max_length=3)),
                ('precio', djmoney.models.fields.MoneyField(decimal_places=0, default_currency='CLP', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('capacidad', models.IntegerField(default=1)),
                ('ocupada', models.BooleanField(default=False)),
            ],
        ),
    ]
