# Generated by Django 3.2.9 on 2021-11-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_mesa_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together=set(),
        ),
    ]
