# Generated by Django 3.2.9 on 2021-11-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211117_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
