# Generated by Django 3.2.9 on 2021-11-23 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_mesa_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='session_key',
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.mesa')),
            ],
        ),
    ]
