# Generated by Django 3.2.9 on 2021-11-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211123_0213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserva',
            new_name='Cliente',
        ),
    ]
