# Generated by Django 3.2.9 on 2021-11-23 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_reserva_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.mesa')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menu')),
            ],
        ),
    ]
