# Generated by Django 3.2.9 on 2021-11-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='menus',
            field=models.ManyToManyField(related_name='menus', to='orders.Menu'),
        ),
    ]
