# Generated by Django 3.2.9 on 2021-11-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20211128_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='menus',
            field=models.ManyToManyField(related_name='ingrediente', to='orders.Menu'),
        ),
    ]
