# Generated by Django 3.2.9 on 2021-11-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_ingrediente_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='menus',
            field=models.ManyToManyField(to='orders.Menu'),
        ),
    ]
